name: pdftrick-native mac
on: [push]
jobs:
  test:
    runs-on: macos-latest
    #cc: "clang",
    #cxx: "clang++",
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  deploy:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  
 